// Phase 40 runtime proof - phase-40-autonomous-ops-os
import * as assert from 'assert';
let passed=0,failed=0;
const check=(n,f)=>{try{f();passed++;console.log('  PASS: '+n);}catch(e){failed++;console.error('  FAIL: '+n+' -- '+e.message);}};
console.log('PHASE 40 -- AutonomousOpsOS :: RUNTIME PROOF');
const {AutonomousOpsOS}=await import(`../src/orchestrator.js`);
const os=new AutonomousOpsOS();
const s1=os.register({signal:'test',requiresApproval:false});
check('AutonomousOpsOS registers signal',()=>assert.ok(s1&&s1.id));
check('signal status is open',()=>assert.strictEqual(s1.status,'open'));
const s2=os.register({signal:'approval-required',requiresApproval:true});
check('approval-required signal created',()=>assert.ok(s2&&s2.id));
check('not auto-approved',()=>assert.strictEqual(s2.status,'open'));
const apr=os.approve(s1.id);
check('approve() sets approved',()=>assert.strictEqual(apr.status,'approved'));
check('approvedAt set',()=>assert.ok(apr&&apr.approvedAt));
const rej=os.reject(s2.id);
check('reject() sets rejected',()=>assert.strictEqual(rej.status,'rejected'));
const s3=os.register({signal:'esc-test'});
const esc=os.escalate(s3.id,'threshold exceeded');
check('escalate() works',()=>assert.strictEqual(esc.status,'escalated'));
check('pending() returns array',()=>assert.ok(Array.isArray(os.pending())));
check('dashboard() phase correct',()=>assert.strictEqual(os.dashboard().phase,40));
check('dashboard() has status',()=>assert.ok(typeof os.dashboard().status==='string'));
const al=os.alert('warning','threshold',s1.id);
check('alert() creates alert',()=>assert.ok(al&&al.id));
const ack=os.acknowledgeAlert(al.id);
check('acknowledgeAlert() works',()=>assert.ok(ack&&ack.acknowledged));
console.log('\n  RESULT: '+passed+' passed, '+failed+' failed');
process.exit(failed===0?0:1);
