/**
 * PM2 Ecosystem — Mi-Core + WhatsApp Gateway + 7 SEO Agents + Orchestrator
 * Deploy: pm2 start ecosystem.config.cjs && pm2 save
 *
 * SEO Phase 6.6: 7 SEO agents + orchestrator with per-brand scheduled jobs.
 * Scheduled jobs (all brands): daily-website-crawl, daily-gsc-sync, daily-ga4-sync,
 *   daily-gbp-sync, weekly-citation-scan, weekly-executive-report.
 */
module.exports = {
  apps: [
    // ── Mi-Core (always online) ─────────────────────────────────────────────
    {
      name: 'mi-core',
      script: 'server/dist/index.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      kill_timeout: 10000,
      wait_ready: false,
      listen_timeout: 15000,
      restart_delay: 3000,
      max_restarts: 20,
      min_uptime: 5000,
      exp_backoff_restart_delay: 200,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production' },
      out_file: 'D:/Project/Master/mi-core/logs/pm2-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/pm2-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    // ── WhatsApp Gateway ────────────────────────────────────────────────────
    {
      name: 'mi-whatsapp-gateway',
      script: 'services/whatsapp-ai-gateway/src/index.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      kill_timeout: 10000,
      restart_delay: 3000,
      max_restarts: 20,
      min_uptime: 5000,
      exp_backoff_restart_delay: 200,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production' },
      out_file: 'D:/Project/Master/mi-core/logs/pm2-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/pm2-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    // ── 7 SEO Agents (Phase 6.6) ────────────────────────────────────────────
    {
      name: 'seo-agent-crawler',
      script: 'SEO/agents/connectors/seo-crawler-agent.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { AGENT_PORT: '4011', AGENT_NAME: 'crawler', NODE_ENV: 'production' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-crawler-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-crawler-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'seo-agent-gsc',
      script: 'SEO/agents/connectors/seo-gsc-agent.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { AGENT_PORT: '4021', AGENT_NAME: 'gsc', NODE_ENV: 'production' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-gsc-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-gsc-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'seo-agent-ga4',
      script: 'SEO/agents/connectors/seo-ga4-agent.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { AGENT_PORT: '4022', AGENT_NAME: 'ga4', NODE_ENV: 'production' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-ga4-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-ga4-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'seo-agent-gbp',
      script: 'SEO/agents/connectors/seo-gbp-agent.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { AGENT_PORT: '4023', AGENT_NAME: 'gbp', NODE_ENV: 'production' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-gbp-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-gbp-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'seo-agent-schema',
      script: 'SEO/agents/audit/seo-schema-agent.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { AGENT_PORT: '4014', AGENT_NAME: 'schema', NODE_ENV: 'production' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-schema-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-schema-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'seo-agent-audit',
      script: 'SEO/agents/audit/seo-technical-audit-agent.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { AGENT_PORT: '4012', AGENT_NAME: 'technical-audit', NODE_ENV: 'production' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-audit-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-audit-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'seo-agent-report',
      script: 'SEO/agents/reporting/seo-report-agent.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { AGENT_PORT: '4017', AGENT_NAME: 'report', NODE_ENV: 'production' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-report-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-report-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    // ── SEO Orchestrator (per-brand scheduled jobs) ─────────────────────────
    {
      name: 'seo-orchestrator',
      script: 'SEO/shared/base/seo-orchestrator.js',
      cwd: 'D:/Project/Master/mi-core',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', MI_CORE_PORT: '4001' },
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: 'D:/Project/Master/mi-core/logs/seo-orchestrator-out.log',
      error_file: 'D:/Project/Master/mi-core/logs/seo-orchestrator-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
