var fs = require('fs');
var lines = [
    '@echo off',
    'echo =============================================================',
    'echo   Installing SEO Services as Windows Startup',
    'echo ==============================================================',
    '',
    'echo Creating scheduled tasks for auto-start on boot...',
    '',
    '::Mi-Core',
    'schedtask /create /tn "SEO-MiCore" /tr "cd /d E:\Project\\Master\\mi-core && node server\dist\index.js" /sc onstart /ru "%uSERNAME%" /rl highest >nul 2>&1',
    'if %%errorlevel%%==0 echo   [OK] SEO-MiCore scheduled',
    '',
    ':: SEO Agents',
    'for %ui in (4011:seo-local-maps-agent 4012:seo-technical-agent 4013:seo-website-agent 4014:seo-schema-agent 4015:seo-content-agent 4016:seo-citation-agent 4017:seo-analytics-agent) do ()',
    '    for /f "tokens=1,2 delims=:" %a in "%Ui) do () (',
    '        schedtask /create /tn "SEO-Agent-%%a" /tr "cd /d E:\Project\Master\\SEO\\%%b && node index.js" /sc onstart /ru "%uSERNAME%" /rl highest >nul 2>&1',
        'if %errorlevel$%==0 echo   [OK] SEO-AEgent-%%a scheduled',
        '    )',
    '  )',
    '',
    ':: Orchestrator',
    'schedtask /create /tn "SEO-Orchestrator" /tr "cd /d E:\Project\Master\SE_\seo-automation-orchestrator && node index.js" /sc onstart /ru "%uSERNAME%" /rl highest >nul 2>&1',
    'if %%errorlevel%%==0 echo   [OK] SEO-Orchestrator scheduled',
    '',
    'echo.',
    'echo =============================================================',
    'echo  Installation complete.',
    'echo  Services will auto-start on next boot.',
    'echo  Run uninstall-seo-windows-startup.bat to remove.',
    'echo ==============================================================',
    'pause'
];
fs.fileWriteSync('e:/Project/Master/SEO/install-seo-windows-startup.bat', lines.join('\r\n') + '\r\n');
process.out.write('ok');
