const fs=require('fs');
const p='d:/Project/Master/mi-core/server/src/routes/qb-mirror-router.ts';
const lines=[
"import { Router, Request, Response } from 'express';",
"import Database from 'better-sqlite3';",
"import path from 'path';",
"import { upsertCompanyFile, logSync, upsertAccounts, upsertCustomers, upsertVendors, upsertItems, upsertInvoices, upsertSalesReceipts, upsertBills, upsertBillPayments, upsertPayments, upsertChecks, upsertDeposits, upsertCreditCardCharges, upsertCreditCardCredits, upsertCreditMemos, upsertPurchaseOrders, upsertEmployees, upsertPayrollChecks, getCompanyFiles, getAccounts, getCustomers, getVendors, getInvoices, getSalesReceipts, getBills, getSyncLog, getChecks, getPayments, getDeposits, getCreditCardCharges, getCreditCardCredits, getEmployees, getPayrollChecks, getMirrorSummary, getMirrorCoverage, getMirrorAllReport } from '../quickbooks/qb-mirror-db';",
"import { parseAllEntities } from '../quickbooks/qb-xml-parser';",
"const router = Router();",
"const MI_CORE_ROOT = process.env.MI_CORE_ROOT || path.resolve(__dirname, '../../..');",
"const DATA_DIR = process.env.MI_DATA_DIR || path.join(MI_CORE_ROOT, 'data');",
"const QB_AGENT_DB_PATH = path.join(DATA_DIR, 'qb-agent.db');",
"router.post('/ingest', (req, res) => {",
"  try {",
"    const { company_file_id, company_name, company_file_path, machine_id, machine_hostname, entity_type, records } = req.body;",
"    if (!company_file_id || !entity_type || !Array.isArray(records)) return res.status(400).json({ error: 'company_file_id, entity_type, and records[] are required' });",
"    upsertCompanyFile({ company_file_id, company_name, company_file_path, machine_id, machine_hostname });",
"    const upsertFns = { accounts: upsertAccounts, customers: upsertCustomers, vendors: upsertVendors, items: upsertItems, invoices: upsertInvoices, sales_receipts: upsertSalesReceipts, bills: upsertBills, bill_payments: upsertBillPayments, payments: upsertPayments, checks: upsertChecks, deposits: upsertDeposits, credit_card_charges: upsertCreditCardCharges, credit_card_credits: upsertCreditCardCredits, credit_memos: upsertCreditMemos, purchase_orders: upsertPurchaseOrders, employees: upsertEmployees, payroll_checks: upsertPayrollChecks };",
"    const fn = upsertFns[entity_type];",
"    if (!fn) return res.status(400).json({ error: `Unknown entity_type: ${entity_type}` });",
"    const count = fn(company_file_id, records);",
"    logSync(company_file_id, machine_id || '', entity_type, count);",
"    res.json({ ok: true, entity_type, records_upserted: count });",
"  } catch (err) { res.status(500).json({ error: err.message || String(err) }); }",
"});",
"router.get('/summary', (req, res) => { try { const company = req.query.company; res.json({ ok: true, summary: getMirrorSummary(company), companies: getCompanyFiles() }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/coverage', (req, res) => { try { const company = req.query.company; res.json({ ok: true, coverage: getMirrorCoverage(company) }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/report', (req, res) => { try { const company = req.query.company; res.json({ ok: true, report: getMirrorAllReport(company) }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/companies', (req, res) => { try { res.json({ ok: true, companies: getCompanyFiles() }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/store-sync', (req, res) => {",
"  try {",
"    const machineId = req.query.machine_id;",
"    const allMachines = !machineId || machineId === 'all';",
"    const db = new Database(QB_AGENT_DB_PATH, { readonly: true, fileMustExist: true });",
"    try {",
"      const machines = db.prepare('SELECT * FROM machines ORDER BY last_seen_at DESC').all();",
"      const files = allMachines ? db.prepare('SELECT * FROM qb_files ORDER BY machine_id, enabled DESC, store_code, file_id').all() : db.prepare('SELECT * FROM qb_files WHERE machine_id = ? ORDER BY enabled DESC, store_code, file_id').all(machineId);",
"      const cycles = allMachines ? db.prepare('SELECT * FROM sync_cycles ORDER BY started_at DESC LIMIT 100').all() : db.prepare('SELECT * FROM sync_cycles WHERE machine_id = ? ORDER BY started_at DESC LIMIT 50').all(machineId);",
"      const statusRow = db.prepare('SELECT (SELECT COUNT(*) FROM machines) AS total_machines, (SELECT COUNT(*) FROM machines WHERE status=\\'online\\') AS online_machines, (SELECT COUNT(*) FROM commands WHERE status=\\'pending\\') AS pending_commands').get();",
"      const recent_errors = db.prepare('SELECT * FROM error_reports ORDER BY received_at DESC LIMIT 10').all();",
"      res.json({ ok: true, machine_id: allMachines ? 'all' : machineId, status: { ...statusRow, recent_errors, timestamp: new Date().toISOString() }, machines, files, cycles, mirror_companies: getCompanyFiles() });",
"    } finally { db.close(); }",
"  } catch (err) { res.status(500).json({ ok: false, error: err.message || String(err) }); }",
"});",
"router.get('/accounts', (req, res) => { try { const data = getAccounts(req.query.company); res.json({ ok: true, count: data.length, accounts: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/customers', (req, res) => { try { const data = getCustomers(req.query.company); res.json({ ok: true, count: data.length, customers: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/vendors', (req, res) => { try { const data = getVendors(req.query.company); res.json({ ok: true, count: data.length, vendors: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/invoices', (req, res) => { try { const { company, from, to, unpaid } = req.query; const data = getInvoices(company, from, to, unpaid === '1' || unpaid === 'true'); const total_amount = data.reduce((s, r) => s + ((r.total_amount)||0), 0); const outstanding = data.filter(r => !r.is_paid).reduce((s, r) => s + ((r.amount_due)||0), 0); res.json({ ok: true, count: data.length, total_amount, outstanding, invoices: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/receipts', (req, res) => { try { const { company, from, to } = req.query; const data = getSalesReceipts(company, from, to); const total = data.reduce((s, r) => s + ((r.total_amount)||0), 0); res.json({ ok: true, count: data.length, total_amount: total, receipts: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/bills', (req, res) => { try { const { company, unpaid } = req.query; const data = getBills(company, unpaid === '1' || unpaid === 'true'); const total_due = data.filter(r => !r.is_paid).reduce((s, r) => s + ((r.amount_due)||0), 0); res.json({ ok: true, count: data.length, total_due, bills: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/checks', (req, res) => { try { const { company, from, to } = req.query; const data = getChecks(company, from, to); res.json({ ok: true, count: data.length, checks: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/payments', (req, res) => { try { const { company, from, to } = req.query; const data = getPayments(company, from, to); res.json({ ok: true, count: data.length, payments: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/deposits', (req, res) => { try { const { company, from, to } = req.query; const data = getDeposits(company, from, to); res.json({ ok: true, count: data.length, deposits: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/credit-card-charges', (req, res) => { try { const { company, from, to } = req.query; const data = getCreditCardCharges(company, from, to); res.json({ ok: true, count: data.length, credit_card_charges: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/credit-card-credits', (req, res) => { try { const { company, from, to } = req.query; const data = getCreditCardCredits(company, from, to); res.json({ ok: true, count: data.length, credit_card_credits: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/employees', (req, res) => { try { const data = getEmployees(req.query.company).map(({ ssn, ...employee }) => employee); res.json({ ok: true, count: data.length, employees: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/payroll-checks', (req, res) => { try { const { company, from, to } = req.query; const data = getPayrollChecks(company, from, to); res.json({ ok: true, count: data.length, payroll_checks: data }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/sync-log', (req, res) => { try { const limit = parseInt(req.query.limit || '50', 10); res.json({ ok: true, log: getSyncLog(req.query.company, limit) }); } catch (err) { res.status(500).json({ error: err.message || String(err) }); } });",
"router.get('/pl', (req, res) => {",
"  try {",
"    const { company, from, to } = req.query;",
"    const accounts = getAccounts(company);",
"    const receipts = getSalesReceipts(company, from, to);",
"    const invoices = getInvoices(company, from, to);",
"    const bills = getBills(company);",
"    const income_accounts = accounts.filter(a => a.account_type === 'Income' || a.account_type === 'OtherIncome');",
"    const expense_accounts = accounts.filter(a => a.account_type === 'Expense' || a.account_type === 'OtherExpense' || a.account_type === 'CostOfGoodsSold');",
"    const total_income = income_accounts.reduce((s, a) => s + ((a.balance)||0), 0);",
"    const total_expense = expense_accounts.reduce((s, a) => s + ((a.balance)||0), 0);",
"    const total_sales = receipts.reduce((s, r) => s + ((r.total_amount)||0), 0) + invoices.filter(i => i.is_paid).reduce((s, i) => s + ((i.total_amount)||0), 0);",
"    const outstanding_ar = invoices.filter(i => !i.is_paid).reduce((s, i) => s + ((i.amount_due)||0), 0);",
"    const outstanding_ap = bills.filter(b => !b.is_paid).reduce((s, b) => s + ((b.amount_due)||0), 0);",
"    res.json({ ok: true, period: { from: from || null, to: to || null }, income: { total: total_income, accounts: income_accounts }, expense: { total: total_expense, accounts: expense_accounts }, net_income: total_income - total_expense, total_sales, outstanding_ar, outstanding_ap });",
"  } catch (err) { res.status(500).json({ error: err.message || String(err) }); }",
"});",
"export { router as qbMirrorRouter };",
"const rawIngestRouter = Router();",
"const QBXML_RESPONSE_ENTITY_KEYS = { AccountQueryRs:'accounts', CustomerQueryRs:'customers', VendorQueryRs:'vendors', ItemQueryRs:'items', InvoiceQueryRs:'invoices', SalesReceiptQueryRs:'sales_receipts', BillQueryRs:'bills', BillPaymentCheckQueryRs:'bill_payments', ReceivePaymentQueryRs:'payments', CheckQueryRs:'checks', DepositQueryRs:'deposits', CreditCardChargeQueryRs:'credit_card_charges', CreditCardCreditQueryRs:'credit_card_credits', CreditMemoQueryRs:'credit_memos', PurchaseOrderQueryRs:'purchase_orders', EmployeeQueryRs:'employees', PayrollItemWageQueryRs:'payroll_checks', PaycheckQueryRs:'payroll_checks' };",
"function detectQueriedEntityKeys(xml, requestName) {",
"  const found = new Set();",
"  for (const [tag, entityKey] of Object.entries(QBXML_RESPONSE_ENTITY_KEYS)) { if (xml.includes(`<${tag}`)) found.add(entityKey); }",
"  const normalizedRequestName = requestName.trim();",
"  const requestEntity = QBXML_RESPONSE_ENTITY_KEYS[normalizedRequestName] || QBXML_RESPONSE_ENTITY_KEYS[normalizedRequestName.replace(/Rq$/, 'Rs')] || QBXML_RESPONSE_ENTITY_KEYS[normalizedRequestName.replace(/Query$/, 'QueryRs')];",
"  if (requestEntity) found.add(requestEntity);",
"  return [...found];",
"}",
"rawIngestRouter.post('/ingest', (req, res) => {",
"  try {",
"    const apiKey = req.headers['x-qb-api-key'] || '';",
"    const expectedKey = process.env.QB_API_KEY || process.env.QBWC_PASS || '';",
"    if (expectedKey && apiKey !== expectedKey) return res.status(401).json({ error: 'Unauthorized' });",
"    const xml = Buffer.isBuffer(req.body) ? req.body.toString('utf8') : typeof req.body === 'string' ? req.body : '';",
"    if (!xml) return res.status(400).json({ error: 'Empty body' });",
"    const requestName = req.headers['x-qb-request-name'] || '';",
"    const companyFilePath = req.headers['x-company-file'] || 'laptop1-default';",
"    const machine_id = req.headers['x-machine-id'] || 'laptop1';",
"    const company_file_id = Buffer.from(companyFilePath).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, 32);",
"    upsertCompanyFile({ company_file_id, company_name: undefined, company_file_path: companyFilePath, machine_id, machine_hostname: machine_id });",
"    const entities = parseAllEntities(xml);",
"    const results = {};",
"    if (entities.accounts.length) { upsertAccounts(company_file_id, entities.accounts); results.accounts = entities.accounts.length; logSync(company_file_id, machine_id, 'accounts', entities.accounts.length); }",
"    if (entities.customers.length) { upsertCustomers(company_file_id, entities.customers); results.customers = entities.customers.length; logSync(company_file_id, machine_id, 'customers', entities.customers.length); }",
"    if (entities.vendors.length) { upsertVendors(company_file_id, entities.vendors); results.vendors = entities.vendors.length; logSync(company_file_id, machine_id, 'vendors', entities.vendors.length); }",
"    if (entities.items.length) { upsertItems(company_file_id, entities.items); results.items = entities.items.length; logSync(company_file_id, machine_id, 'items', entities.items.length); }",
"    if (entities.invoices.length) { upsertInvoices(company_file_id, entities.invoices); results.invoices = entities.invoices.length; logSync(company_file_id, machine_id, 'invoices', entities.invoices.length); }",
"    if (entities.sales_receipts.length) { upsertSalesReceipts(company_file_id, entities.sales_receipts); results.sales_receipts = entities.sales_receipts.length; logSync(company_file_id, machine_id, 'sales_receipts', entities.sales_receipts.length); }",
"    if (entities.bills.length) { upsertBills(company_file_id, entities.bills); results.bills = entities.bills.length; logSync(company_file_id, machine_id, 'bills', entities.bills.length); }",
"    if (entities.bill_payments.length) { upsertBillPayments(company_file_id, entities