#!/usr/bin/env python3
"""Rebuild qb-dashboard.html from scratch with Phase 1 + Phase 2 (Charts)"""
import os

html = open(r'd:/Project/Master/mi-core/ui/qb-dashboard.html', 'w', encoding='utf-8')

OUT = []

def L(s=''):
    OUT.append(s)

L('<!DOCTYPE html>')
L('<html lang="en">')
L('<head>')
L('<meta charset="UTF-8">')
L('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
L('<title>QB Mirror Dashboard</title>')
L('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.19.0/dist/tabler-icons.min.css">')
L('<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>')
L('<style>')
L('*{box-sizing:border-box;margin:0;padding:0}')
L(':root{--bg:#0a0a0f;--card:#12121a;--border:#1e1e2e;--accent:#3b82f6;--green:#10b981;--red:#ef4444;--yellow:#f59e0b;--text:#e2e8f0;--muted:#64748b;--surface-0:#0a0a0f;--surface-1:#12121a;--surface-2:#1a1a28;--text-primary:#e2e8f0;--text-secondary:#94a3b8;--text-muted:#64748b;--text-accent:#60a5fa;--text-success:#34d399;--text-danger:#f87171;--text-warning:#fbbf24;--bg-accent:#1e3a5f;--bg-success:#064e3b;--bg-danger:#450a0a;--bg-warning:#451a03;--fill-accent:#3b82f6;--fill-success:#10b981;--fill-danger:#ef4444;--border-strong:#2e2e44;--radius:6px}')
L('body{font-family:\'Segoe UI\',system-ui,sans-serif;background:var(--surface-0);color:var(--text-primary);font-size:13px}')
L('.shell{display:flex;height:100vh}')
L('.sidebar{width:200px;min-width:200px;background:var(--surface-1);border-right:1px solid var(--border);display:flex;flex-direction:column;overflow-y:auto}')
L('.sidebar-logo{padding:16px 14px 12px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:8px}')
L('.sidebar-logo span{font-size:14px;font-weight:600;color:var(--text-primary)}')
L('.nav-section{padding:8px 0}')
L('.nav-label{font-size:10px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em;padding:6px 14px 4px}')
L('.nav-item{display:flex;align-items:center;gap:8px;padding:7px 14px;cursor:pointer;color:var(--text-secondary);font-size:12px;transition:background .1s}')
L('.nav-item:hover{background:var(--surface-2);color:var(--text-primary)}')
L('.nav-item.active{background:var(--bg-accent);color:var(--text-accent);font-weight:600}')
L('.nav-item i{font-size:15px;flex-shrink:0}')
L('.main{flex:1;display:flex;flex-direction:column;overflow:hidden}')
L('.topbar{padding:10px 20px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:10px;background:var(--surface-1)}')
L('.topbar-title{font-size:15px;font-weight:600;flex:1;min-width:120px}')
L('.date-range select{font-size:12px;padding:4px 8px;border:1px solid var(--border-strong);border-radius:var(--radius);background:var(--surface-2);color:var(--text-primary);cursor:pointer}')
L('.btn-refresh{display:flex;align-items:center;gap:5px;padding:5px 12px;border:1px solid var(--border-strong);border-radius:var(--radius);background:transparent;color:var(--text-secondary);cursor:pointer;font-size:12px}')
L('.btn-refresh:hover{background:var(--surface-2);color:var(--text-primary)}')
L('.sync-badge{font-size:11px;padding:2px 8px;border-radius:20px;background:var(--bg-warning);color:var(--text-warning)}')
L('.sync-badge.synced{background:var(--bg-success);color:var(--text-success)}')
L('.content{flex:1;overflow-y:auto;padding:16px 20px}')
L('.stat-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin-bottom:16px}')
L('.stat{background:var(--surface-1);border-radius:var(--radius);padding:12px 14px;border:1px solid var(--border)}')
L('.stat-label{font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px}')
L('.stat-value{font-size:22px;font-weight:700;color:var(--text-primary)}')
L('.stat-value.green{color:var(--text-success)}')
L('.stat-value.red{color:var(--text-danger)}')
L('.stat-value.amber{color:var(--text-warning)}')
L('.stat-sub{font-size:11px;color:var(--text-muted);margin-top:2px}')
L('.hero-audit{display:grid;grid-template-columns:minmax(280px,1.1fr) minmax(300px,1.9fr);gap:14px;margin-bottom:14px}')
L('.audit-decision{background:linear-gradient(135deg,#102033,#10151f);border:1px solid #23405c;border-radius:10px;padding:16px}')
L('.decision-label{font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px}')
L('.decision-title{font-size:22px;font-weight:700;line-height:1.2;margin-bottom:8px}')
L('.decision-title.green{color:var(--text-success)}')
L('.decision-title.amber{color:var(--text-warning)}')
L('.decision-title.red{color:var(--text-danger)}')
L('.decision-copy{font-size:12px;line-height:1.55;color:var(--text-secondary);max-width:620px}')
L('.audit-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}')
L('.mini-metric{background:var(--surface-1);border:1px solid var(--border);border-radius:8px;padding:11px 12px}')
L('.mini-metric strong{display:block;font-size:19px;margin-bottom:3px}')
L('.mini-metric span{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted)}')
L('.audit-grid{display:grid;grid-template-columns:1.35fr .65fr;gap:14px;margin-bottom:14px}')
L('.callout-list{display:grid;gap:8px;padding:12px}')
L('.callout{background:var(--surface-1);border:1px solid var(--border);border-radius:var(--radius);padding:10px 12px;font-size:12px;display:flex;justify-content:space-between;align-items:center}')
L('.callout-left{display:flex;align-items:center;gap:8px}')
L('.callout-dot{width:7px;height:7px;border-radius:50%;flex-shrink:0}')
L('.callout-dot.green{background:var(--green)}')
L('.callout-dot.red{background:var(--red)}')
L('.callout-dot.amber{background:var(--yellow)}')
L('.callout-dot.blue{background:var(--accent)}')
L('.callout-amount{font-weight:600;font-size:13px}')
L('.section-title{font-size:11px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em;padding:14px 20px 8px;border-bottom:1px solid var(--border);position:sticky;top:0;background:var(--surface-0);z-index:1}')
L('.view{display:none}.view.active{display:block}')
L('.no-data{text-align:center;color:var(--text-muted);padding:48px;font-size:13px}')
L('.no-data i{font-size:32px;display:block;margin-bottom:8px}')
L('table{width:100%;border-collapse:collapse;font-size:12px}')
L('thead th{background:var(--surface-1);padding:8px 10px;text-align:left;font-size:10px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid var(--border);white-space:nowrap}')
L('tbody tr{border-bottom:1px solid rgba(255,255,255,0.03)}')
L('tbody tr:hover{background:rgba(255,255,255,0.02)}')
L('tbody td{padding:7px 10px;vertical-align:middle}')
L('.amount{text-align:right;font-variant-numeric:tabular-nums}')
L('td.amount{font-variant-numeric:tabular-nums}')
L('.mono{font-family:\'Cascadia Code\',\'Consolas\',monospace;font-size