/**
 * Phase 34G — Evidence Engine
 * Collects and stores all evidence for an engineering task:
 * commits, PR, screenshots, logs, API output, test results, coverage.
 */

import * as fs from 'fs';
import * as path from 'path';

const GLOBAL_DIR   = process.env.GLOBAL_DIR || 'D:/Project/Master/.local-agent-global';
const EVIDENCE_DIR = path.join(GLOBAL_DIR, 'engineering', 'evidence');
if (!fs.existsSync(EVIDENCE_DIR)) fs.mkdirSync(EVIDENCE_DIR, { recursive: true });

export interface EvidenceRecord {
  task_id:      string;
  type:         'commit' | 'pr' | 'screenshot' | 'log' | 'api_output' | 'test_result' | 'coverage' | 'review';
  content:      string;
  timestamp:    string;
  source:       string;
}

export interface TaskEvidence {
  task_id:    string;
  collected:  EvidenceRecord[];
  report_path: string;
}

// ── Store evidence ────────────────────────────────────────────────────────────

export function addEvidence(record: Omit<EvidenceRecord, 'timestamp'>): EvidenceRecord {
  const full: EvidenceRecord = { ...record, timestamp: new Date().toISOString() };

  const taskDir = path.join(EVIDENCE_DIR, record.task_id);
  if (!fs.existsSync(taskDir)) fs.mkdirSync(taskDir, { recursive: true });

  const evFile = path.join(taskDir, 'evidence.json');
  let existing: EvidenceRecord[] = [];
  try {
    if (fs.existsSync(evFile)) existing = JSON.parse(fs.readFileSync(evFile, 'utf-8'));
  } catch { /* ignore */ }

  existing.push(full);
  fs.writeFileSync(evFile, JSON.stringify(existing, null, 2));
  return full;
}

export function getEvidence(taskId: string): EvidenceRecord[] {
  const evFile = path.join(EVIDENCE_DIR, taskId, 'evidence.json');
  if (!fs.existsSync(evFile)) return [];
  try {
    return JSON.parse(fs.readFileSync(evFile, 'utf-8'));
  } catch {
    return [];
  }
}

// ── Generate evidence report ──────────────────────────────────────────────────

export function generateEvidenceReport(
  taskId:    string,
  objective: string,
  model:     string,
): string {
  const evidence = getEvidence(taskId);
  const now      = new Date().toISOString().slice(0, 10);

  const byType = (type: EvidenceRecord['type']) =>
    evidence.filter(e => e.type === type);

  const section = (title: string, records: EvidenceRecord[]) => {
    if (!records.length) return `### ${title}\n_No evidence collected._\n`;
    return `### ${title}\n${records.map(r =>
      `- **${r.source}** (${r.timestamp.slice(0, 19)})\n  \`\`\`\n  ${r.content.slice(0, 500)}\n  \`\`\``
    ).join('\n')}\n`;
  };

  const report = `# Engineering Evidence Report
> Task: ${taskId}
> Date: ${now}
> Model: ${model}

## Objective
${objective}

## Evidence Summary
| Type | Count |
|------|-------|
| Commits | ${byType('commit').length} |
| PRs | ${byType('pr').length} |
| Test Results | ${byType('test_result').length} |
| API Output | ${byType('api_output').length} |
| Logs | ${byType('log').length} |
| Screenshots | ${byType('screenshot').length} |
| Reviews | ${byType('review').length} |

${section('Commits', byType('commit'))}
${section('Pull Requests', byType('pr'))}
${section('Test Results', byType('test_result'))}
${section('API Output', byType('api_output'))}
${section('Code Review', byType('review'))}
${section('Logs', byType('log'))}

---
_Generated by Mi Engineering Division — Phase 34G_
`;

  const reportPath = path.join(EVIDENCE_DIR, taskId, 'ENGINEERING_EVIDENCE_REPORT.md');
  fs.writeFileSync(reportPath, report);
  return reportPath;
}
