const fs=require('fs') 
const c=fs.readFileSync('api/index.php') 
const CRLF=Buffer.from([13,10]) 
const Q=Buffer.from([39]) 
const ARROW=Buffer.from([61,62]) 
const EQTRUE=Buffer.concat([ARROW,Buffer.from('true,')]) 
const EQLBR=Buffer.concat([ARROW,Buffer.from('[')]) 
const EQPAGE=Buffer.concat([ARROW,Buffer.from([36,112,97,103,101,44])]) 
const EQBUTTONS=Buffer.concat([ARROW,Buffer.from([36,98,117,116,116,111,110,115,44])]) 
const EQSECTIONS=Buffer.concat([ARROW,Buffer.from([36,115,101,99,116,105,111,110,115,44])]) 
const EQSETTINGS=Buffer.concat([ARROW,Buffer.from([36,115,101,116,116,105,110,103,115,93,93,59])]) 
const EQNOINDEX=Buffer.concat([ARROW,Buffer.from([36,110,111,105,110,100,101,120,93,93,59])]) 
const header=Buffer.concat([Buffer.from('    header('),Q,Buffer.from('Content-Type: application/json; charset=utf-8'),Q,Buffer.from(');'),CRLF]) 
const resp=Buffer.concat([Buffer.from('    http_response_code(200);'),CRLF]) 
const echoPre=Buffer.concat([Buffer.from('    echo json_encode(['),Q,Buffer.from('ok'),Q,EQTRUE,Q,Buffer.from('preview'),Q,EQTRUE,Q,Buffer.from('data'),Q,EQLBR,Q,Buffer.from('page'),Q,EQPAGE,Q,Buffer.from('buttons'),Q,EQBUTTONS,Q,Buffer.from('sections'),Q,EQSECTIONS,Q,Buffer.from('settings'),Q,EQSETTINGS,CRLF,Buffer.from('    exit;')]) 
const previewOld=Buffer.concat([header,resp,echoPre]) 
fs.writeFileSync('out.txt','found:'+c.includes(previewOld)) 
fs.writeFileSync('out.txt',previewOld.toString()) 
fs.writeFileSync('hex.txt',previewOld.slice(0,20).toString('hex')) 
