/**
 * oss-worker-registry.ts — the governed OSS worker selected for each phase.
 *
 * One primary worker per phase (Part A1 requires ≥1 per phase 12–20). The
 * registry now covers every phase 12–100 contiguously per MI_PROGRAM_V5/V6.
 * Phases 51–100 that have not yet been deepened carry an in-engine scaffold
 * worker; ROI-priority phases (53/56/60/62/67/74/81/99) run real engines.
 * Specs mirror the OSS governance manifest; the registry is the runtime view.
 */
import type { OssWorkerSpec } from './oss-execution-contract';

export const OSS_WORKERS: OssWorkerSpec[] = [
  { id: 'otel', name: 'OpenTelemetry', phase: 12, businessRole: 'trace/outcome memory export', ownerDivision: 'intelligence', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'module', module: '@opentelemetry/api' }, fallback: 'in-engine JsonStore failure/outcome memory' },
  { id: 'langgraph', name: 'LangGraph', phase: 13, businessRole: 'multi-agent handoff orchestration', ownerDivision: 'engineering', license: 'MIT', licenseRisk: 'low', probe: { kind: 'module', module: '@langchain/langgraph' }, fallback: 'in-engine dispatch/handoff/review' },
  { id: 'temporal', name: 'Temporal', phase: 14, businessRole: 'durable approval workflow', ownerDivision: 'operations', license: 'MIT', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 7233 }, fallback: 'in-engine propose/approve/reject lifecycle' },
  { id: 'opa', name: 'Open Policy Agent', phase: 15, businessRole: 'guardrail policy decisions', ownerDivision: 'it', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 8181 }, fallback: 'in-engine GuardrailEngine + whitelist' },
  { id: 'duckdb', name: 'DuckDB', phase: 16, businessRole: 'multi-location KPI analytics', ownerDivision: 'operations', license: 'MIT', licenseRisk: 'low', probe: { kind: 'module', module: 'duckdb' }, fallback: 'in-engine LocationKPILayer rollups' },
  { id: 'openfga', name: 'OpenFGA', phase: 17, businessRole: 'tenant/relationship authorization', ownerDivision: 'it', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 8080 }, fallback: 'in-engine TenantIsolation guard' },
  { id: 'graphology', name: 'Graphology (NetworkX-equiv)', phase: 18, businessRole: 'knowledge graph traversal', ownerDivision: 'data-platform', license: 'MIT', licenseRisk: 'low', probe: { kind: 'module', module: 'graphology' }, fallback: 'in-engine adjacency BFS impact/path' },
  { id: 'statsforecast', name: 'StatsForecast', phase: 19, businessRole: 'time-series forecasting', ownerDivision: 'finance', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'env', env: 'STATSFORECAST_URL' }, fallback: 'in-engine linear/growth ForecastEngine' },
  { id: 'openobserve', name: 'OpenObserve', phase: 20, businessRole: 'continuous monitoring + autonomy log', ownerDivision: 'executive', license: 'AGPL-3.0', licenseRisk: 'medium', probe: { kind: 'tcp', host: '127.0.0.1', port: 5080 }, fallback: 'in-engine AutonomyLog + Uptime-Kuma rollback' },
  { id: 'chatwoot', name: 'Chatwoot', phase: 21, businessRole: 'customer conversation/feedback ingestion', ownerDivision: 'operations', license: 'MIT', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 3000 }, fallback: 'in-engine feedback-ingestion + sentiment' },
  { id: 'posthog', name: 'PostHog', phase: 22, businessRole: 'channel/revenue analytics', ownerDivision: 'marketing', license: 'MIT', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 8000 }, fallback: 'in-engine channel-performance engine' },
  { id: 'uptimekuma', name: 'Uptime Kuma', phase: 23, businessRole: 'store-ops uptime/checklist monitoring', ownerDivision: 'operations', license: 'MIT', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 3001 }, fallback: 'in-engine store-health + checklist compliance' },
  { id: 'erpnext', name: 'ERPNext', phase: 24, businessRole: 'procurement/inventory/COGS', ownerDivision: 'finance', license: 'GPL-3.0', licenseRisk: 'medium', probe: { kind: 'tcp', host: '127.0.0.1', port: 8001 }, fallback: 'in-engine vendor/ingredient/COGS engines' },
  { id: 'orangehrm', name: 'OrangeHRM', phase: 25, businessRole: 'HR/labor/scheduling', ownerDivision: 'operations', license: 'GPL-3.0', licenseRisk: 'medium', probe: { kind: 'tcp', host: '127.0.0.1', port: 8002 }, fallback: 'in-engine labor-cost + schedule-risk engines' },
  { id: 'comfyui', name: 'ComfyUI', phase: 26, businessRole: 'creative asset generation', ownerDivision: 'creative', license: 'GPL-3.0', licenseRisk: 'medium', probe: { kind: 'tcp', host: '127.0.0.1', port: 8188 }, fallback: 'in-engine creative-brief + asset registry' },
  { id: 'keycloak', name: 'Keycloak', phase: 27, businessRole: 'access control / identity', ownerDivision: 'it', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 8443 }, fallback: 'in-engine access-control + audit-log engines' },
  { id: 'n8n', name: 'n8n', phase: 28, businessRole: 'workflow fabric automation', ownerDivision: 'it', license: 'Sustainable Use License', licenseRisk: 'medium', probe: { kind: 'tcp', host: '127.0.0.1', port: 5678 }, fallback: 'in-engine workflow registry + dedupe + replay' },
  { id: 'openmetadata', name: 'OpenMetadata', phase: 29, businessRole: 'data catalog / quality / lineage', ownerDivision: 'data-platform', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'tcp', host: '127.0.0.1', port: 8585 }, fallback: 'in-engine catalog + freshness + lineage engines' },
  { id: 'grafana', name: 'Grafana', phase: 30, businessRole: 'executive command-center dashboards', ownerDivision: 'executive', license: 'AGPL-3.0', licenseRisk: 'medium', probe: { kind: 'tcp', host: '127.0.0.1', port: 3030 }, fallback: 'in-engine CEO command-center renderer' },
  { id: 'supplier-hub', name: 'ODOO Community (Supply Chain)', phase: 31, businessRole: 'supply chain + vendor delivery + logistics', ownerDivision: 'operations', license: 'GPL-3.0', licenseRisk: 'medium', probe: { kind: 'module', module: 'odoorpc' }, fallback: 'in-engine supply-chain + vendor delivery signals' },
  { id: 'legal-hub', name: 'PostgreSQL Legal Hub', phase: 32, businessRole: 'legal + contract + compliance + regulatory', ownerDivision: 'legal', license: 'PostgreSQL', licenseRisk: 'low', probe: { kind: 'module', module: 'pg' }, fallback: 'in-engine legal-compliance + contract registry' },
  { id: 'innovate-db', name: 'PostgreSQL Innovation Pipeline', phase: 33, businessRole: 'menu R&D + product pipeline + supplier innovation', ownerDivision: 'product', license: 'PostgreSQL', licenseRisk: 'low', probe: { kind: 'module', module: 'pg' }, fallback: 'in-engine product-innovation + R&D pipeline' },
  { id: 'fleet-mgmt', name: 'ODOO Community (Fleet)', phase: 34, businessRole: 'delivery fleet + vehicle ops + driver management', ownerDivision: 'operations', license: 'GPL-3.0', licenseRisk: 'medium', probe: { kind: 'module', module: 'odoorpc' }, fallback: 'in-engine fleet-transport + driver signals' },
  { id: 'fraudscore-oss', name: 'FraudScore OSS', phase: 35, businessRole: 'payment fraud + refund abuse + chargeback detection', ownerDivision: 'fraud-risk', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'FRAUDSCORE_URL' }, fallback: 'in-engine fraud-risk + refund abuse signals' },
  { id: 'rewards-engine', name: 'PostgreSQL Loyalty Engine', phase: 36, businessRole: 'rewards + retention + VIP lifecycle management', ownerDivision: 'customer-loyalty', license: 'PostgreSQL', licenseRisk: 'low', probe: { kind: 'module', module: 'pg' }, fallback: 'in-engine customer-loyalty + VIP lifecycle signals' },
  { id: 'doordash-api', name: 'DoorDash API', phase: 37, businessRole: 'DoorDash + aggregator + partner onboarding', ownerDivision: 'partner-channel', license: 'Proprietary', licenseRisk: 'medium', probe: { kind: 'env', env: 'DOORDASH_API_URL' }, fallback: 'in-engine partner-channel + DoorDash aggregator signals' },
  { id: 'sql-ledger', name: 'SQL-Ledger', phase: 38, businessRole: 'GL + AP/AR + reconciliation + tax', ownerDivision: 'finance-accounting', license: 'GPL-2.0', licenseRisk: 'low', probe: { kind: 'module', module: 'better-sqlite3' }, fallback: 'in-engine finance-accounting + GL signals' },
  { id: 'airbyte', name: 'Airbyte', phase: 39, businessRole: 'ETL pipeline + data warehouse + BI reporting', ownerDivision: 'data-warehouse', license: 'MIT', licenseRisk: 'low', probe: { kind: 'module', module: 'airbyte-sdk' }, fallback: 'in-engine data-warehouse + ETL signals' },
  { id: 'autonomy-core', name: 'Temporal / n8n Autonomy Core', phase: 40, businessRole: 'self-healing + autonomous orchestration + rollback', ownerDivision: 'autonomous-ops', license: 'MIT', licenseRisk: 'low', probe: { kind: 'module', module: '@temporalio/client' }, fallback: 'in-engine autonomous-ops + self-healing signals' },
  { id: 'ai-support-core', name: 'Rasa OSS', phase: 41, businessRole: 'AI-powered customer support + ticket triage', ownerDivision: 'ai-customer-support', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_41_URL' }, fallback: 'in-engine ai-customer-support signals' },
  { id: 'tax-hub', name: 'TaxJar / OpenTaxJar', phase: 42, businessRole: 'Tax preparation + filing + audit defense', ownerDivision: 'tax-compliance', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_42_URL' }, fallback: 'in-engine tax-compliance signals' },
  { id: 'mkt-automation', name: 'Mautic', phase: 43, businessRole: 'Multi-channel marketing + campaign orchestration', ownerDivision: 'marketing-automation', license: 'GPL-3.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_43_URL' }, fallback: 'in-engine marketing-automation signals' },
  { id: 'supplier-registry', name: 'ERPNext Community', phase: 44, businessRole: 'Supplier onboarding + scoring + relationship mgmt', ownerDivision: 'supplier-management', license: 'GPL-3.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_44_URL' }, fallback: 'in-engine supplier-management signals' },
  { id: 'store-exp-core', name: 'PostHog + Appsmith', phase: 45, businessRole: 'In-store experience + queue management + ambience', ownerDivision: 'store-experience', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_45_URL' }, fallback: 'in-engine store-experience signals' },
  { id: 'qa-core', name: 'Great Expectations', phase: 46, businessRole: 'Food quality + service quality + compliance audits', ownerDivision: 'quality-assurance', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_46_URL' }, fallback: 'in-engine quality-assurance signals' },
  { id: 'dr-core', name: 'Velero + Restic', phase: 47, businessRole: 'Business continuity + disaster recovery + backup', ownerDivision: 'disaster-recovery', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_47_URL' }, fallback: 'in-engine disaster-recovery signals' },
  { id: 'km-core', name: 'BookStack / WikiJS', phase: 48, businessRole: 'Internal knowledge base + SOP + training library', ownerDivision: 'knowledge-management', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_48_URL' }, fallback: 'in-engine knowledge-management signals' },
  { id: 'ir-core', name: 'PostgreSQL + Superset', phase: 49, businessRole: 'Investor reporting + cap table + stakeholder updates', ownerDivision: 'investor-relations', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_49_URL' }, fallback: 'in-engine investor-relations signals' },
  { id: 'strategy-core', name: 'Metabase + n8n', phase: 50, businessRole: 'Long-term strategy + roadmap + market analysis', ownerDivision: 'strategic-planning', license: 'AGPL-3.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_50_URL' }, fallback: 'in-engine strategic-planning signals' },
  { id: 'ph51-core', name: 'in-engine (scaffold)', phase: 51, businessRole: 'Enterprise digital twin - model CEO/stores/projects/teams/vendors/systems', ownerDivision: 'enterprise-digital-twin', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_51_URL' }, fallback: 'in-engine enterprise-digital-twin signals' },
  { id: 'ph52-core', name: 'in-engine (scaffold)', phase: 52, businessRole: 'Enterprise simulator - whole-company what-if', ownerDivision: 'enterprise-simulator', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_52_URL' }, fallback: 'in-engine enterprise-simulator signals' },
  { id: 'cfo-ai-core', name: 'PostgreSQL + StatsForecast', phase: 53, businessRole: 'CFO AI — revenue + margin + labor + cash flow', ownerDivision: 'finance', license: 'PostgreSQL', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_53_URL' }, fallback: 'in-engine CFO forecasting + financial-risk signals' },
  { id: 'ph54-core', name: 'in-engine (scaffold)', phase: 54, businessRole: 'Vendor intelligence - suppliers/contracts/costs/performance', ownerDivision: 'vendor-intelligence', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_54_URL' }, fallback: 'in-engine vendor-intelligence signals' },
  { id: 'ph55-core', name: 'in-engine (scaffold)', phase: 55, businessRole: 'Procurement AI - purchase planning/reorder/inventory forecasting', ownerDivision: 'procurement-ai', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_55_URL' }, fallback: 'in-engine procurement-ai signals' },
  { id: 'talent-core', name: 'OrangeHRM + Metabase', phase: 56, businessRole: 'Talent intelligence — skills + performance + capacity + retention risk', ownerDivision: 'talent-intelligence', license: 'GPL-3.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_56_URL' }, fallback: 'in-engine talent-intelligence signals' },
  { id: 'ph57-core', name: 'in-engine (scaffold)', phase: 57, businessRole: 'Recruitment AI - JD/candidate scoring/interview summaries', ownerDivision: 'recruitment-ai', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_57_URL' }, fallback: 'in-engine recruitment-ai signals' },
  { id: 'ph58-core', name: 'in-engine (scaffold)', phase: 58, businessRole: 'Training AI - SOP trainer/onboarding/learning paths', ownerDivision: 'training-ai', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_58_URL' }, fallback: 'in-engine training-ai signals' },
  { id: 'ph59-core', name: 'in-engine (scaffold)', phase: 59, businessRole: 'Knowledge evolution - gap finding/doc suggestions/graph updates', ownerDivision: 'knowledge-evolution', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_59_URL' }, fallback: 'in-engine knowledge-evolution signals' },
  { id: 'org-health-core', name: 'Grafana + PostgreSQL', phase: 60, businessRole: 'Organizational health — team + project + company health monitoring', ownerDivision: 'org-health', license: 'AGPL-3.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_60_URL' }, fallback: 'in-engine organizational-health signals' },
  { id: 'ph61-core', name: 'in-engine (scaffold)', phase: 61, businessRole: 'Executive strategy advisor', ownerDivision: 'executive-strategy-advisor', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_61_URL' }, fallback: 'in-engine executive-strategy-advisor signals' },
  { id: 'market-intel-core', name: 'Apache Superset + SerpAPI', phase: 62, businessRole: 'Market intelligence — external demand + opportunity signal', ownerDivision: 'market-intelligence', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_62_URL' }, fallback: 'in-engine market-intelligence signals' },
  { id: 'ph63-core', name: 'in-engine (scaffold)', phase: 63, businessRole: 'Competitor intelligence engine', ownerDivision: 'competitor-intelligence', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_63_URL' }, fallback: 'in-engine competitor-intelligence signals' },
  { id: 'ph64-core', name: 'in-engine (scaffold)', phase: 64, businessRole: 'Expansion planning engine', ownerDivision: 'expansion-planning', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_64_URL' }, fallback: 'in-engine expansion-planning signals' },
  { id: 'ph65-core', name: 'in-engine (scaffold)', phase: 65, businessRole: 'Store growth predictor', ownerDivision: 'store-growth-predictor', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_65_URL' }, fallback: 'in-engine store-growth-predictor signals' },
  { id: 'ph66-core', name: 'in-engine (scaffold)', phase: 66, businessRole: 'Franchise intelligence', ownerDivision: 'franchise-intelligence', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_66_URL' }, fallback: 'in-engine franchise-intelligence signals' },
  { id: 'sentiment-core', name: 'Chatwoot + NLP sentiment', phase: 67, businessRole: 'Customer sentiment — review/customer risk + growth signal', ownerDivision: 'customer-sentiment', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_67_URL' }, fallback: 'in-engine customer-sentiment signals' },
  { id: 'ph68-core', name: 'in-engine (scaffold)', phase: 68, businessRole: 'Brand intelligence', ownerDivision: 'brand-intelligence', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_68_URL' }, fallback: 'in-engine brand-intelligence signals' },
  { id: 'ph69-core', name: 'in-engine (scaffold)', phase: 69, businessRole: 'Reputation defense system', ownerDivision: 'reputation-defense', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_69_URL' }, fallback: 'in-engine reputation-defense signals' },
  { id: 'ph70-core', name: 'in-engine (scaffold)', phase: 70, businessRole: 'Executive war room', ownerDivision: 'executive-war-room', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_70_URL' }, fallback: 'in-engine executive-war-room signals' },
  { id: 'ph71-core', name: 'in-engine (scaffold)', phase: 71, businessRole: 'AI board of directors', ownerDivision: 'ai-board-of-directors', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_71_URL' }, fallback: 'in-engine ai-board-of-directors signals' },
  { id: 'ph72-core', name: 'in-engine (scaffold)', phase: 72, businessRole: 'Multi-agent executive council', ownerDivision: 'multi-agent-executive-council', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_72_URL' }, fallback: 'in-engine multi-agent-executive-council signals' },
  { id: 'ph73-core', name: 'in-engine (scaffold)', phase: 73, businessRole: 'Strategic consensus engine', ownerDivision: 'strategic-consensus', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_73_URL' }, fallback: 'in-engine strategic-consensus signals' },
  { id: 'risk-forecast-core', name: 'StatsForecast', phase: 74, businessRole: 'Corporate risk forecasting — future operational + financial risk', ownerDivision: 'risk-forecasting', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_74_URL' }, fallback: 'in-engine corporate-risk-forecasting signals' },
  { id: 'ph75-core', name: 'in-engine (scaffold)', phase: 75, businessRole: 'Business scenario generator', ownerDivision: 'business-scenario-generator', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_75_URL' }, fallback: 'in-engine business-scenario-generator signals' },
  { id: 'ph76-core', name: 'in-engine (scaffold)', phase: 76, businessRole: 'Acquisition evaluation AI', ownerDivision: 'acquisition-evaluation', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_76_URL' }, fallback: 'in-engine acquisition-evaluation signals' },
  { id: 'ph77-core', name: 'in-engine (scaffold)', phase: 77, businessRole: 'Investment evaluation AI', ownerDivision: 'investment-evaluation', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_77_URL' }, fallback: 'in-engine investment-evaluation signals' },
  { id: 'ph78-core', name: 'in-engine (scaffold)', phase: 78, businessRole: 'Corporate portfolio manager', ownerDivision: 'corporate-portfolio-manager', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_78_URL' }, fallback: 'in-engine corporate-portfolio-manager signals' },
  { id: 'ph79-core', name: 'in-engine (scaffold)', phase: 79, businessRole: 'Enterprise optimization engine', ownerDivision: 'enterprise-optimization', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_79_URL' }, fallback: 'in-engine enterprise-optimization signals' },
  { id: 'ph80-core', name: 'in-engine (scaffold)', phase: 80, businessRole: 'Executive decision laboratory', ownerDivision: 'executive-decision-lab', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_80_URL' }, fallback: 'in-engine executive-decision-lab signals' },
  { id: 'self-healing-core', name: 'Temporal + Uptime Kuma', phase: 81, businessRole: 'Self-healing infrastructure — stability + auto-recovery + rollback', ownerDivision: 'self-healing', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_81_URL' }, fallback: 'in-engine self-healing-infrastructure signals' },
  { id: 'ph82-core', name: 'in-engine (scaffold)', phase: 82, businessRole: 'Self-healing projects', ownerDivision: 'self-healing-projects', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_82_URL' }, fallback: 'in-engine self-healing-projects signals' },
  { id: 'ph83-core', name: 'in-engine (scaffold)', phase: 83, businessRole: 'Self-healing knowledge', ownerDivision: 'self-healing-knowledge', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_83_URL' }, fallback: 'in-engine self-healing-knowledge signals' },
  { id: 'ph84-core', name: 'in-engine (scaffold)', phase: 84, businessRole: 'Self-healing workflows', ownerDivision: 'self-healing-workflows', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_84_URL' }, fallback: 'in-engine self-healing-workflows signals' },
  { id: 'ph85-core', name: 'in-engine (scaffold)', phase: 85, businessRole: 'Self-evolving skill ecosystem', ownerDivision: 'self-evolving-skills', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_85_URL' }, fallback: 'in-engine self-evolving-skills signals' },
  { id: 'ph86-core', name: 'in-engine (scaffold)', phase: 86, businessRole: 'Self-evolving agent ecosystem', ownerDivision: 'self-evolving-agents', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_86_URL' }, fallback: 'in-engine self-evolving-agents signals' },
  { id: 'ph87-core', name: 'in-engine (scaffold)', phase: 87, businessRole: 'Continuous organizational improvement', ownerDivision: 'continuous-org-improvement', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_87_URL' }, fallback: 'in-engine continuous-org-improvement signals' },
  { id: 'ph88-core', name: 'in-engine (scaffold)', phase: 88, businessRole: 'Enterprise autonomy layer', ownerDivision: 'enterprise-autonomy', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_88_URL' }, fallback: 'in-engine enterprise-autonomy signals' },
  { id: 'ph89-core', name: 'in-engine (scaffold)', phase: 89, businessRole: 'Autonomous executive operations', ownerDivision: 'autonomous-executive-ops', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_89_URL' }, fallback: 'in-engine autonomous-executive-ops signals' },
  { id: 'ph90-core', name: 'in-engine (scaffold)', phase: 90, businessRole: 'Autonomous company management', ownerDivision: 'autonomous-company-management', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_90_URL' }, fallback: 'in-engine autonomous-company-management signals' },
  { id: 'ph91-core', name: 'in-engine (scaffold)', phase: 91, businessRole: 'Corporate digital consciousness', ownerDivision: 'corporate-digital-consciousness', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_91_URL' }, fallback: 'in-engine corporate-digital-consciousness signals' },
  { id: 'ph92-core', name: 'in-engine (scaffold)', phase: 92, businessRole: 'Long-term strategic memory 10+ years', ownerDivision: 'longterm-strategic-memory', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_92_URL' }, fallback: 'in-engine longterm-strategic-memory signals' },
  { id: 'ph93-core', name: 'in-engine (scaffold)', phase: 93, businessRole: 'Predictive organizational memory', ownerDivision: 'predictive-org-memory', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_93_URL' }, fallback: 'in-engine predictive-org-memory signals' },
  { id: 'ph94-core', name: 'in-engine (scaffold)', phase: 94, businessRole: 'Enterprise foresight engine', ownerDivision: 'enterprise-foresight', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_94_URL' }, fallback: 'in-engine enterprise-foresight signals' },
  { id: 'ph95-core', name: 'in-engine (scaffold)', phase: 95, businessRole: 'CEO shadow model', ownerDivision: 'ceo-shadow-model', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_95_URL' }, fallback: 'in-engine ceo-shadow-model signals' },
  { id: 'ph96-core', name: 'in-engine (scaffold)', phase: 96, businessRole: 'Executive succession simulator', ownerDivision: 'executive-succession-simulator', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_96_URL' }, fallback: 'in-engine executive-succession-simulator signals' },
  { id: 'ph97-core', name: 'in-engine (scaffold)', phase: 97, businessRole: 'Enterprise survival simulator', ownerDivision: 'enterprise-survival-simulator', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_97_URL' }, fallback: 'in-engine enterprise-survival-simulator signals' },
  { id: 'ph98-core', name: 'in-engine (scaffold)', phase: 98, businessRole: 'Black swan detection engine', ownerDivision: 'black-swan-detection', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_98_URL' }, fallback: 'in-engine black-swan-detection signals' },
  { id: 'guardian-core', name: 'Falco + Open Policy Agent', phase: 99, businessRole: 'Corporate guardian — protect data + revenue + reputation + operations', ownerDivision: 'corporate-guardian', license: 'Apache-2.0', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_99_URL' }, fallback: 'in-engine corporate-guardian signals' },
  { id: 'ph100-core', name: 'in-engine (scaffold)', phase: 100, businessRole: 'Jarvis Singularity - final vision', ownerDivision: 'jarvis-singularity', license: 'MIT', licenseRisk: 'low', probe: { kind: 'env', env: 'PHASE_100_URL' }, fallback: 'in-engine jarvis-singularity signals' },
];


export function workersForPhase(phase: number): OssWorkerSpec[] {
  return OSS_WORKERS.filter((w) => w.phase === phase);
}

export function getWorker(id: string): OssWorkerSpec | undefined {
  return OSS_WORKERS.find((w) => w.id === id);
}
