import os
e1=chr(0x1F4BE);e2=chr(0x2705);e3=chr(0x1F4CA);e4=chr(0x1F512);e5=chr(0x26A0)+chr(0xFE0F)
NL=chr(10)
p1="docs/PHASE_1_1_SHEET_RECOVERY_REPORT.md"
p2="docs/PHASE_1_1_STORE_MAPPING_LOCK_REPORT.md"
s=chr(35)+" Phase 1.1 "+chr(8212)+" Google Sheet Failure Recovery Report"+NL
s+=NL+"**Project:** WhatsApp AI Gateway"+NL
s+="**Date:** 2026-06-04"+NL
s+="**Status:** IMPLEMENTED"+NL
s+=NL+"---"+NL
s+=NL+"## What Was Built"+NL
s+=NL+"A `sheet_write_queue` table and retry scheduler guarantee no confirmed data is ever lost."+NL
s+=NL+"### Table: `sheet_write_queue`"+NL
s+=NL+"```sql"+NL
s+="CREATE TABLE IF NOT EXISTS sheet_write_queue ("+NL
s+="  id               INTEGER PRIMARY KEY AUTOINCREMENT,"+NL
s+="  workflow_type    TEXT NOT NULL,"+NL
s+="  store_id         TEXT,"+NL
s+="  payload_json     TEXT NOT NULL,"+NL
s+="  target_sheet     TEXT,"+NL
s+="  status           TEXT NOT NULL DEFAULT "+chr(39)+"PENDING"+chr(39)+","+NL
s+="  attempt_count    INTEGER NOT NULL DEFAULT 0,"+NL
s+="  last_error       TEXT,"+NL
s+="  created_at       TEXT DEFAULT (datetime("+chr(39)+"now"+chr(39)+")),"+NL
s+="  last_attempt_at  TEXT,"+NL
s+="  sent_at          TEXT"+NL
s+=")"+NL
s+="```"+NL
s+=NL+"Status values: PENDING | SENT | FAILED"+NL
s+=NL+"Indexes: `idx_queue_status`"+NL
s+=NL+"---"+NL
s+=NL+"## How It Works"+NL
s+=NL+"1. Workflow confirmed "+chr(8594)+" attempt Google Sheet write"+NL
s+="2. If write fails "+chr(8594)+" enqueue({ workflowType, storeId, payload, lastError })"+NL
s+="3. User sees: "+chr(8220)+e1+" Saved locally. Google Sheet write queued."+chr(8221)+NL
s+="4. Retry scheduler runs every 5 minutes"+NL
s+="5. Up to 10 attempts before marking FAILED"+NL
s+="6. Manager alert still sends even if sheet is queued"+NL
s+=NL+"---"+NL
s+=NL+"## User Experience"+NL
s+=NL+"| Scenario | User Sees |"+NL
s+="|----------|-----------|"+NL
s+="| Sheet write succeeds | "++e2+" Daily Entry Logged. "+e3+" Recorded to Google Sheet. |"+NL
