const fs=require('fs')
const NL=String.fromCharCode(10)
const Q=String.fromCharCode(39)
const GT=String.fromCharCode(62)
const D=String.fromCharCode(36)
const LBR=String.fromCharCode(91)
const RBR=String.fromCharCode(93)
const lines=[]
lines.push('const fs = require(\"fs\");')
lines.push('const c = fs.readFileSync(\"api/index.php\", \"utf8\");')
lines.push('const Q=String.fromCharCode(39);')
lines.push('const NL=String.fromCharCode(10);')
lines.push('const GT=String.fromCharCode(62);')
lines.push('const D=String.fromCharCode(36);')
lines.push('const LBR=String.fromCharCode(91);')
lines.push('const RBR=String.fromCharCode(93);')
lines.push('const EQ=String.fromCharCode(61,62);')
lines.push(')'
lines.push('// Step 1: Find and insert migrate_staff_training_v3 function')
lines.push('const search = \"migration_staff_training_v2\";')
lines.push('const idx = c.indexOf(search, 19000);')
lines.push('const closeIdx = c.indexOf(\"}\", idx);')
lines.push('const insertAt = closeIdx + 1;')
lines.push('const c2 = c.slice(0, insertAt) + newFunc + c.slice(insertAt);')
lines.push('console.log(\"Inserted v3 function\");')
lines.push(')'
lines.push('// Step 2: Update preview route')
lines.push('const oldPreview = \"    header(\" + Q + \"Content-Type: application/json; charset=utf-8\" + Q + \");\" + NL + \"    http_response_code(200);\" + NL + \"    echo json_encode(\" + LBR + Q + \"ok\" + Q + EQ + \"true,\" + Q + \"preview\" + Q + EQ + \"true,\" + Q + \"data\" + Q + EQ + LBR + Q + \"page\" + Q + EQ + D + \"page,\" + Q + \"buttons\" + Q + EQ + D + \"buttons,\" + Q + \"sections\" + Q + EQ + D + \"sections,\" + Q + \"settings\" + Q + EQ + D + \"settings\" + RBR + RBR + \");\" + NL + \"    exit;\";')
lines.push('const newPreview = \"    \" + D + \"noindex = in_array(\" + D + \"page\" + LBR + Q + \"visibility\" + Q + \"], \" + LBR + Q + \"unlisted\" + Q + \",\" + Q + \"staff_only\" + Q + \"], true);\" + NL + \"    header(\" + Q + \"Content-Type: application/json; charset=utf-8\" + Q + \");\" + NL + \"    http_response_code(200);\" + NL + \"    echo json_encode(\" + LBR + Q + \"ok\" + Q + EQ + \"true,\" + Q + \"preview\" + Q + EQ + \"true,\" + Q + \"data\" + Q + EQ + LBR + Q + \"page\" + Q + EQ + D + \"page,\" + Q + \"buttons\" + Q + EQ + D + \"buttons,\" + Q + \"sections\" + Q + EQ + D + \"sections,\" + Q + \"settings\" + Q + EQ + D + \"settings,\" + Q + \"noindex\" + Q + EQ + D + \"noindex\" + RBR + RBR + \");\" + NL + \"    exit;\";')
lines.push('let c3 = c2.replace(oldPreview, newPreview, 1);')
lines.push('console.log(\"Preview updated:\" + (c2 !== c3));')
lines.push(')'
lines.push('// Step 3: Update main links route')
lines.push('const oldLinks = \"    header(\" + Q + \"Content-Type: application/json; charset=utf-8\" + Q + \");\" + NL + \"    http_response_code(200);\" + NL + \"    echo json_encode(\" + LBR + Q + \"ok\" + Q + EQ + \"true,\" + Q + \"data\" + Q + EQ + LBR + Q + \"page\" + Q + EQ + D + \"page,\" + Q + \"buttons\" + Q + EQ + D + \"buttons,\" + Q + \"sections\" + Q + EQ + D + \"sections,\" + Q + \"settings\" + Q + EQ + D + \"settings\" + RBR + RBR + \");\" + NL + \"    exit;\";')
lines.push('const newLinks = \"    \" + D + \"noindex = in_array(\" + D + \"page\" + LBR + Q + \"visibility\" + Q + \"], \" + LBR + Q + \"unlisted\" + Q + \",\" + Q + \"staff_only\" + Q + \"], true);\" + NL + \"    header(\" + Q + \"Content-Type: application/json; charset=utf-8\" + Q + \");\" + NL + \"    http_response_code(200);\" + NL + \"    echo json_encode(\" + LBR + Q + \"ok\" + Q + EQ + \"true,\" + Q + \"data\" + Q + EQ + LBR + Q + \"page\" + Q + EQ + D + \"page,\" + Q + \"buttons\" + Q + EQ + D + \"buttons,\" + Q + \"sections\" + Q + EQ + D + \"sections,\" + Q + \"settings\" + Q + EQ + D + \"settings,\" + Q + \"noindex\" + Q + EQ + D + \"noindex\" + RBR + RBR + \");\" + NL + \"    exit;\";')
lines.push('let c4 = c3.replace(oldLinks, newLinks, 1);')
lines.push('console.log(\"Links updated:\" + (c3 !== c4));')
lines.push(')'
lines.push('// Save the file')
lines.push('fs.writeFileSync(\"api/index.php\", c4);')
lines.push('console.log(\"Saved. Length:\" + c4.length);')
fs.writeFileSync('script.js',lines.join(NL))
