const {chromium}=require('@playwright/test');const path=require('path'),fs=require('fs');
const BASE='https://dashboard.bakudanramen.com',EMAIL='qa.bot@bakudanramen.com',PASS='QA-Preview-2026!';
const OUT=path.join(__dirname,'..','evidence','mobile-cert');fs.mkdirSync(OUT+'/shots',{recursive:true});fs.mkdirSync(OUT+'/logs',{recursive:true});
const DEVS=[{n:'iPhone-15',w:393,h:852,ua:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1',m:true},{n:'iPhone-15-Plus',w:430,h:932,ua:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1',m:true},{n:'Galaxy-S23',w:360,h:780,ua:'Mozilla/5.0 (Linux; Android 14; Pixel 7) AppleWebKit/537.36 Chrome/120.0.0.0 Mobile Safari/537.36',m:true},{n:'iPad-Air',w:820,h:1180,ua:'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Safari/604.1',m:false}];
const ERR=['Something went wrong','Internal Error','Fatal error','SQLSTATE','Undefined','500 Internal'];
let total={p:0,f:0,shots:0};
async function shot(p,n){await p.screenshot({path:OUT+'/shots/'+n+'.png'});total.shots++;}
async function chk(p,url,n,ho){let errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});let st='unk',ok=true;try{let r=await p.goto(url,{waitUntil:'domcontentloaded',timeout:25000});st=r.status();}catch(e){errs.push('NAV:'+e.message.slice(0,80));}await p.waitForTimeout(1500);let txt='';try{txt=await p.evaluate(()=>document.body?document.body.innerText:'',{timeout:8000});}catch(e){}let hasInt=false;for(let e of ERR)if(txt.includes(e))hasInt=true;let hov=ho?await p.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+2).catch(()=>false):null;await shot(p,n);ok=!hasInt&&txt.length>50&&st<400&&errs.length===0;if(ok)total.p++;else total.f++;return{n,url,st,ok,errs:errs.slice(0,3),hov,txtLen:txt.length};}
async function login(p){await p.goto(BASE+'/login',{waitUntil:'networkidle',timeout:20000});await p.fill('input[name="email"], input[type="email"]',EMAIL);await p.fill('input[name="password"], input[type="password"]',PASS);await p.click('button[type="submit"], input[type="submit"]');try{await p.waitForURL(/overview|dashboard|my-tasks/,{timeout:15000});}catch(e){await p.goto(BASE+'/overview',{waitUntil:'domcontentloaded',timeout:15000});}}
async function run(){let results=[];
for(let d of DEVS){console.log('\n== '+d.n+' ('+d.w+'x'+d.h+') ==');const br=await chromium.launch({headless:true});const ctx=await br.newContext({viewport:{width:d.w,height:d.h},userAgent:d.ua,isMobile:d.m,hasTouch:d.m});const p=await ctx.newPage();const devErrs=[];p.on('pageerror',e=>devErrs.push('[PE]'+e.message));p.on('console',m=>{if(m.type()==='error')devErrs.push('[CE]'+m.text());});try{await login(p);console.log('LOGIN OK: '+p.url());}catch(e){console.log('LOGIN FAIL: '+e.message);results.push({d:d.n,ok:false,err:'Login failed'});await br.close();continue;}
const routes=[{u:'/overview',n:d.n+'-01-Overview',ho:true},{u:'/overview/drilldown/cash-risk',n:d.n+'-02-CashRisk',ho:false},{u:'/overview/drilldown/overdue-bills',n:d.n+'-03-OverdueBills',ho:false},{u:'/overview/drilldown/critical-tasks',n:d.n+'-04-CriticalTasks',ho:false},{u:'/overview/drilldown/compliance-risk',n:d.n+'-05-ComplianceRisk',ho:false},{u:'/overview/drilldown/penalty',n:d.n+'-06-Penalty',ho:false},{u:'/my-tasks',n:d.n+'-07-MyTasks',ho:false},{u:'/bills',n:d.n+'-08-Bills',ho:false},{u:'/calendar',n:d.n+'-09-Calendar',ho:false},{u:'/inbox',n:d.n+'-10-Inbox',ho:false}];
for(let r of routes){const res=await chk(p,BASE+r.u,r.n,r.ho);const m=res.ok?'✅':'❌';console.log(m+' '+r.n+' ['+res.st+'] len='+res.txtLen+(res.errs.length?' ERR:'+res.errs[0]:''));results.push({d:d.n,...res});}
if(devErrs.length){fs.appendFileSync(OUT+'/logs/'+d.n+'-errors.txt',devErrs.join('\n'));}await br.close();}
console.log('\n'+'='.repeat(60)+'\nTOTAL: '+total.p+' pass / '+total.f+' fail / '+total.shots+' screenshots\n'+'='.repeat(60));
fs.writeFileSync(OUT+'/results.json',JSON.stringify({total,results,ts:new Date().toISOString()},null,2));process.exit(total.f>0?1:0);}
run().catch(e=>{console.error('FATAL:',e.message);process.exit(1);});
