import type { ProviderConfig } from '../types.js';

const common = {
  chat: true,
  streaming: true,
  tools: true,
  thinking: false,
  embeddings: false,
  multimodal: true,
  modelDiscovery: true,
};

export const DEFAULT_MODEL_ALIASES: Record<string, string[]> = {
  'claude-opus-4':    ['claude-opus-4.6', 'claude-opus-4', 'claude-opus-4-1-20250805', 'anthropic/claude-opus-4.1'],
  'claude-opus-4-6':  ['claude-opus-4.6', 'claude-opus-4', 'claude-opus-4-1-20250805', 'anthropic/claude-opus-4.1'],
  'claude-opus-4-7':  ['claude-opus-4.6', 'claude-opus-4', 'claude-opus-4-1-20250805', 'anthropic/claude-opus-4.1'],
  'claude-opus-4-8':  ['claude-opus-4.6', 'claude-opus-4', 'claude-opus-4-1-20250805', 'anthropic/claude-opus-4.1'],
  'claude-sonnet-4-6': ['claude-sonnet-4-6', 'claude-sonnet-4-5-20250929', 'claude-sonnet-4-20250514'],
  'gpt-4.1':          ['gpt-4.1', 'openai/gpt-4.1'],
  'gemini-2.5-pro':   ['gemini-2.5-pro', 'google/gemini-2.5-pro'],
  'deepseek-coder':   ['deepseek-coder', 'deepseek-chat'],
  autocomplete:       ['qwen2.5-coder:7b', 'deepseek-coder', 'gpt-4.1-mini'],
  reasoning:          ['claude-opus-4-7', 'claude-opus-4-1-20250805', 'gpt-4.1'],
  coding:             ['deepseek-chat', 'claude-opus-4-7', 'gpt-4.1'],
};

export const DEFAULT_ROUTES: Record<string, string[]> = {
  reasoning:    ['antigravity', 'opusmax', 'anthropic', 'openrouter', 'openai'],
  coding:       ['antigravity', 'opusmax', 'deepseek', 'openrouter', 'openai', 'ollama'],
  autocomplete: ['ollama', 'deepseek', 'openai'],
  fallback:     ['antigravity', 'opusmax', 'openrouter', 'anthropic', 'openai', 'gemini', 'deepseek', 'ollama'],
};

export function defaultProviders(timeoutMs: number): ProviderConfig[] {
  return [
    {
      id: 'antigravity',
      label: 'Antigravity NKQ',
      kind: 'anthropic',
      baseURL: 'https://api.nkq.vn/v1',
      defaultModel: 'claude-opus-4',
      models: ['claude-opus-4'],
      aliases: { 'claude-opus-4-7': ['claude-opus-4'], 'claude-opus-4-6': ['claude-opus-4'] },
      keys: [],
      enabled: false,
      priority: 10,   // PRIMARY — burns 250 included requests first
      timeoutMs,
      capabilities: { ...common },
    },
    {
      id: 'opusmax',
      label: 'OpusMax',
      kind: 'openai-compatible',
      baseURL: 'https://opusmax.shop/v1',
      defaultModel: 'gpt-5.4',
      models: ['gpt-5.4', 'gpt-5.4-mini', 'claude-opus-4.6', 'claude-opus-4'],
      aliases: { 'claude-opus-4-7': ['gpt-5.4'], 'claude-opus-4-8': ['gpt-5.4'], 'claude-opus-4-6': ['gpt-5.4'] },
      keys: [],
      enabled: false,
      priority: 20,   // FALLBACK — unlimited, activates after NKQ quota
      timeoutMs,
      capabilities: { ...common, embeddings: true },
    },
    {
      id: 'opusmax-anthropic',
      label: 'OpusMax (Anthropic)',
      kind: 'anthropic',
      baseURL: 'https://opusmax.shop',
      defaultModel: 'claude-opus-4-7',
      models: ['claude-opus-4-7', 'claude-opus-4-6', 'claude-opus-4'],
      aliases: { 'claude-opus-4-7': ['claude-opus-4-7'], 'claude-opus-4-6': ['claude-opus-4-6'] },
      keys: [],
      enabled: false,
      priority: 25,   // FALLBACK after opusmax openai-compat
      timeoutMs,
      capabilities: { ...common },
    },
    {
      id: 'anthropic',
      label: 'Anthropic',
      kind: 'anthropic',
      baseURL: 'https://api.anthropic.com',
      defaultModel: 'claude-opus-4-1-20250805',
      models: ['claude-opus-4-1-20250805', 'claude-sonnet-4-5-20250929', 'claude-sonnet-4-20250514'],
      aliases: {},
      keys: [],
      enabled: false,
      priority: 30,
      timeoutMs,
      headers: { 'anthropic-version': '2023-06-01' },
      capabilities: { ...common, thinking: true },
    },
    {
      id: 'openrouter',
      label: 'OpenRouter',
      kind: 'openai-compatible',
      baseURL: 'https://openrouter.ai/api/v1',
      defaultModel: 'anthropic/claude-opus-4.1',
      models: ['anthropic/claude-opus-4.1', 'anthropic/claude-sonnet-4.5', 'openai/gpt-4.1'],
      aliases: {},
      keys: [],
      enabled: false,
      priority: 40,
      timeoutMs,
      capabilities: { ...common, embeddings: true },
    },
    {
      id: 'openai',
      label: 'OpenAI',
      kind: 'openai-compatible',
      baseURL: 'https://api.openai.com/v1',
      defaultModel: 'gpt-4.1',
      models: ['gpt-4.1', 'gpt-4.1-mini', 'gpt-4o'],
      aliases: {},
      keys: [],
      enabled: false,
      priority: 50,
      timeoutMs,
      capabilities: { ...common, embeddings: true },
    },
    {
      id: 'gemini',
      label: 'Gemini',
      kind: 'openai-compatible',
      baseURL: 'https://generativelanguage.googleapis.com/v1beta/openai',
      defaultModel: 'gemini-2.5-pro',
      models: ['gemini-2.5-pro', 'gemini-2.0-flash'],
      aliases: {},
      keys: [],
      enabled: false,
      priority: 60,
      timeoutMs,
      capabilities: { ...common, thinking: true, embeddings: true },
    },
    {
      id: 'deepseek',
      label: 'DeepSeek',
      kind: 'openai-compatible',
      baseURL: 'https://api.deepseek.com/v1',
      defaultModel: 'deepseek-chat',
      models: ['deepseek-chat', 'deepseek-coder'],
      aliases: {},
      keys: [],
      enabled: false,
      priority: 70,
      timeoutMs,
      capabilities: { ...common },
    },
    {
      id: 'ollama',
      label: 'Ollama Local',
      kind: 'ollama',
      baseURL: 'http://localhost:11434/v1',
      defaultModel: 'qwen2.5-coder:7b',
      models: ['qwen2.5-coder:7b', 'llama3.1', 'deepseek-r1:7b'],
      aliases: {},
      keys: [{ id: 'local', value: 'ollama', active: true }],
      enabled: true,
      priority: 80,
      timeoutMs,
      capabilities: { ...common, embeddings: true },
    },
  ];
}
