/**
 * PROJECT DNA GENERATOR - Master Intelligence Layer
 */
'use strict';
const fs=require('fs'),path=require('path');
const INDEX_PATH=path.join(__dirname,'..','master-indexer','output','MASTER_INDEX.json');
const SUMMARY_PATH=path.join(__dirname,'PROJECT_DNA_SUMMARY.md');
function fmtB(b){if(!b)return'0 B';const k=1024,s=['B','KB','MB','GB'],i=Math.floor(Math.log(b)/Math.log(k));return parseFloat((b/Math.pow(k,i)).toFixed(2))+' '+s[i];}
function genDNA(p,t){const deps=p.dependencies||[];const pd=deps.filter(d=>!d.is_dev).map(d=>'  - '+d.name+' '+d.version);const dd=deps.filter(d=>d.is_dev).map(d=>'  - '+d.name+' '+d.version);const L=[];
L.push('# '+(p.display_name||p.project_name));L.push('');
L.push('<!--');L.push('  PROJECT DNA');L.push('  Generated by: project-dna-generator (Master Intelligence Layer)');
L.push('  Generated at: '+t);L.push('  DO NOT EDIT - Auto-generated from MASTER_INDEX.json');L.push('-->');L.push('');
L.push('## Identity');L.push('');L.push('| Field | Value |');L.push('|-------|-------|');
L.push('| Project Name | '+(p.project_name||'')+' |');
L.push('| Display Name | '+(p.display_name||'')+' |');
L.push('| Path | '+(p.path||'')+' |');
L.push('| Git Remote | '+(p.git_remote||'')+' |');
L.push('| Branch | '+(p.git_branch||'')+' |');
L.push('| Git Status | '+(p.git_status||'')+' |');L.push('');
L.push('## Technology');L.push('');L.push('| Field | Value |');L.push('|-------|-------|');
L.push('| Primary Language | '+(p.language_main||'')+' |');
L.push('| Secondary Lang | '+(p.language_secondary||'')+' |');
L.push('| Framework | '+(p.framework||'')+' |');L.push('');
L.push('## Business Metadata');L.push('');L.push('| Field | Value |');L.push('|-------|-------|');
L.push('| Purpose | UNKNOWN - NEEDS REVIEW |');
L.push('| Business Function | UNKNOWN - NEEDS REVIEW |');
L.push('| Owner | '+(p.owner||'UNKNOWN - NEEDS REVIEW')+' |');
L.push('| Criticality | '+(p.criticality||'P2')+' |');
L.push('| Release Status | '+(p.status==='active'?'Active':(p.status||'Active'))+' |');L.push('');
L.push('## Code Metrics');L.push('');L.push('| Field | Value |');L.push('|-------|-------|');
L.push('| Total Files | '+(p.total_files!=null?p.total_files.toLocaleString():'0')+' |');
L.push('| Total Lines | '+(p.total_lines!=null?p.total_lines.toLocaleString():'0')+' |');
L.push('| Size | '+fmtB(p.size_bytes)+' |');L.push('');
L.push('## Dependencies');L.push('');
L.push('**Production ('+pd.length+'):**');L.push('');
if(pd.length>0){pd.forEach(d=>L.push(d));}else{L.push('  _None_');}
L.push('');L.push('**Dev ('+dd.length+'):**');L.push('');
if(dd.length>0){dd.forEach(d=>L.push(d));}else{L.push('  _None_');}
L.push('');
L.push('## Quality & Health');L.push('');L.push('| Field | Value |');L.push('|-------|-------|');
L.push('| Health Score | 75 - UNKNOWN |');
L.push('| QA Coverage | UNKNOWN - NEEDS REVIEW |');
L.push('| Known Bugs | None recorded |');
L.push('| Known Risks | UNKNOWN - NEEDS REVIEW |');L.push('');
L.push('## Indexing');L.push('');L.push('| Field | Value |');L.push('|-------|-------|');
L.push('| Last Indexed At | '+t+' |');L.push('');
L.push('---');L.push('_Auto-generated by project-dna-generator. Update UNKNOWN fields with actual data._');
return L.join(String.fromCharCode(10));}

function genSummary(projects,t){const L=[];
L.push('# PROJECT DNA SUMMARY');L.push('');
L.push('> Generated: '+t);L.push('');
L.push('**Total Projects:** '+projects.length);L.push('');
L.push('| # | Project | Language | Framework | Criticality | Status | Files |');
L.push('|---|---------|----------|-----------|-------------|--------|-------|');
projects.forEach((p,i)=>{
L.push('| '+(i+1)+' | '+(p.display_name||p.project_name||'')+' | '+(p.language_main||'')+' | '+(p.framework||'')+' | '+(p.criticality||'P2')+' | '+(p.status==='active'?'Active':(p.status||'Active'))+' | '+(p.total_files||0)+' |');
});
L.push('');L.push('---');
L.push('_Auto-generated summary. See individual PROJECT_DNA.md files for details._');
return L.join(String.fromCharCode(10));}

function main(){
console.log('=== PROJECT DNA GENERATOR ===');console.log('');
if(!fs.existsSync(INDEX_PATH)){console.error('ERROR: MASTER_INDEX.json not found at:',INDEX_PATH);process.exit(1);}
let idx;try{idx=JSON.parse(fs.readFileSync(INDEX_PATH,'utf8'));}catch(e){console.error('Parse error:',e.message);process.exit(1);}
const projects=idx.projects||[];
const generatedAt=new Date().toISOString();
console.log('Loaded:',projects.length,'projects');console.log('');
let ok=0,fail=0;
for(const p of projects){
if(!p.path){console.warn('  [SKIP] No path:',p.project_name);fail++;continue;}
if(!fs.existsSync(p.path)){console.warn('  [SKIP] Missing dir:',p.path);fail++;continue;}
try{fs.writeFileSync(path.join(p.path,'PROJECT_DNA.md'),genDNA(p,generatedAt),'utf8');
console.log('  [OK]',p.display_name||p.project_name);ok++;}
catch(e){console.error('  [FAIL]',p.project_name,e.message);fail++;}}
console.log('');
fs.writeFileSync(SUMMARY_PATH,genSummary(projects,generatedAt),'utf8');
console.log('Summary:',SUMMARY_PATH);
console.log('');console.log('=== RESULTS ===');
console.log('  Generated:',ok);console.log('  Skipped:',fail);
if(fail>0)process.exit(1);}

main();