/**
 * Repository structure graph: routes, response shapes, imports and roles.
 *
 * Deliberately compact rather than complete. A fragile whole-repository static
 * analysis is worse than a small graph that reliably answers the four questions
 * retrieval actually asks:
 *
 *   which file defines this route, which handler serves it, what does that
 *   handler call, and which tests exercise it.
 *
 * Everything is discovered generically from the AST. No framework, route path,
 * type or filename is hardcoded.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as ts from 'typescript';
import { isBinaryPath, resolveWithinWorktree } from '../llm/tools';
import { extractSymbols, resolveModule, type SymbolSummary } from '../llm/symbols';
import type { StructuralRole } from './types';

const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete', 'options', 'head', 'all']);

export interface RouteDefinition {
  method: string;
  /** Path exactly as written at the call site. */
  routePath: string;
  /** Prefix-composed path when a mount point could be resolved. */
  fullPath: string;
  filePath: string;
  line: number;
  /** Response object keys the handler writes, e.g. res.json({ a, b }). */
  responseKeys: string[];
  /** Identifiers the handler body references, for call-graph edges. */
  referencedIdentifiers: string[];
}

export interface MountPoint {
  prefix: string;
  filePath: string;
  /** Module specifier mounted at the prefix, when resolvable. */
  resolvedPath: string | null;
}

export interface CliCommand {
  name: string;
  filePath: string;
  line: number;
}

export interface FileNode {
  path: string;
  role: StructuralRole;
  symbols: SymbolSummary[];
  /** Repo-relative paths this file imports. */
  imports: string[];
  /** Local binding name -> repo-relative path, so `app.use(x, router)` resolves. */
  importBindings: Record<string, string>;
  /** Mount prefixes declared in this file, with the identifier they mounted. */
  mounts: Array<{ prefix: string; binding: string | null }>;
  /** Repo-relative paths that import this file. */
  importedBy: string[];
  routes: RouteDefinition[];
  cliCommands: CliCommand[];
  /** All string literals, used for exact operational-string matching. */
  stringLiterals: string[];
  bytes: number;
  isTest: boolean;
  isGenerated: boolean;
}

export interface RepoGraph {
  worktreePath: string;
  files: Map<string, FileNode>;
  routes: RouteDefinition[];
  mounts: MountPoint[];
  buildMs: number;
}

const GENERATED_MARKERS = [
  /(^|\/)(dist|build|out|coverage|generated|__generated__|\.next|node_modules)\//,
  /\.(min|bundle)\.[cm]?js$/,
  /\.d\.ts$/,
];

const GENERATED_HEADER = /^\s*(\/\/|\/\*|#)\s*(auto-?generated|generated by|do not edit|@generated)/i;

export function isGeneratedPath(relative: string): boolean {
  return GENERATED_MARKERS.some(pattern => pattern.test(relative));
}

export function isTestPath(relative: string): boolean {
  return (
    /(^|\/)(tests?|specs?|__tests__|t)\//.test(relative) ||
    /[._-](test|spec)\.[cm]?[jt]sx?$/.test(relative)
  );
}

function readSource(absolute: string, maxBytes: number): string | null {
  try {
    const stat = fs.statSync(absolute);
    if (!stat.isFile() || stat.size > maxBytes) return null;
    return fs.readFileSync(absolute, 'utf8');
  } catch {
    return null;
  }
}

/** Joins a mount prefix and a route path into a single normalised path. */
export function composeRoutePath(prefix: string, routePath: string): string {
  const left = prefix.replace(/\/+$/, '');
  const right = routePath.startsWith('/') ? routePath : `/${routePath}`;
  const joined = `${left}${right}`.replace(/\/{2,}/g, '/');
  return joined === '' ? '/' : joined;
}

function objectLiteralKeys(node: ts.Node): string[] {
  const keys: string[] = [];
  const visit = (current: ts.Node): void => {
    if (ts.isObjectLiteralExpression(current)) {
      for (const property of current.properties) {
        const name = property.name?.getText?.();
        if (name) keys.push(name.replace(/['"`]/g, ''));
      }
    }
    current.forEachChild(visit);
  };
  visit(node);
  return [...new Set(keys)];
}

function identifiersIn(node: ts.Node): string[] {
  const names = new Set<string>();
  const visit = (current: ts.Node): void => {
    if (ts.isIdentifier(current)) names.add(current.text);
    current.forEachChild(visit);
  };
  visit(node);
  return [...names];
}

/**
 * Finds the response payload of a handler: keys passed to `.json(...)`,
 * `.send(...)` or returned from the body. Generic over any object with those
 * method names, which is what makes it work beyond Express.
 */
function responseKeysOf(handler: ts.Node, source: ts.SourceFile): string[] {
  const keys: string[] = [];
  const visit = (current: ts.Node): void => {
    if (ts.isCallExpression(current) && ts.isPropertyAccessExpression(current.expression)) {
      const method = current.expression.name.text;
      if (method === 'json' || method === 'send' || method === 'jsonp') {
        for (const argument of current.arguments) keys.push(...objectLiteralKeys(argument));
      }
    }
    if (ts.isReturnStatement(current) && current.expression) {
      keys.push(...objectLiteralKeys(current.expression));
    }
    current.forEachChild(visit);
  };
  visit(handler);
  void source;
  return [...new Set(keys)];
}

function parseRoutesAndMounts(
  relative: string,
  source: ts.SourceFile
): { routes: RouteDefinition[]; mounts: Array<{ prefix: string; binding: string | null }>; cli: CliCommand[] } {
  const routes: RouteDefinition[] = [];
  const mounts: Array<{ prefix: string; binding: string | null }> = [];
  const cli: CliCommand[] = [];

  const visit = (node: ts.Node): void => {
    if (ts.isCallExpression(node) && ts.isPropertyAccessExpression(node.expression)) {
      const method = node.expression.name.text.toLowerCase();
      const [first, ...rest] = node.arguments;

      if (HTTP_METHODS.has(method) && first && ts.isStringLiteralLike(first)) {
        const handler = rest[rest.length - 1];
        const line = source.getLineAndCharacterOfPosition(node.getStart()).line + 1;
        routes.push({
          method: method.toUpperCase(),
          routePath: first.text,
          fullPath: first.text,
          filePath: relative,
          line,
          responseKeys: handler ? responseKeysOf(handler, source) : [],
          referencedIdentifiers: handler ? identifiersIn(handler) : [],
        });
      }

      if (method === 'use' && first && ts.isStringLiteralLike(first)) {
        const mounted = rest[0];
        mounts.push({
          prefix: first.text,
          binding: mounted && ts.isIdentifier(mounted) ? mounted.text : null,
        });
      }

      // Generic CLI command registration: `.command('name')` / `.addCommand('name')`.
      if ((method === 'command' || method === 'addcommand') && first && ts.isStringLiteralLike(first)) {
        cli.push({
          name: first.text,
          filePath: relative,
          line: source.getLineAndCharacterOfPosition(node.getStart()).line + 1,
        });
      }
    }

    // Bare CLI dispatch: `case 'name':` or `cmd === 'name'` inside a main().
    if (ts.isCaseClause(node) && ts.isStringLiteralLike(node.expression)) {
      cli.push({
        name: node.expression.text,
        filePath: relative,
        line: source.getLineAndCharacterOfPosition(node.getStart()).line + 1,
      });
    }

    node.forEachChild(visit);
  };

  visit(source);
  return { routes, mounts, cli };
}

function stringLiteralsOf(source: ts.SourceFile): string[] {
  const literals = new Set<string>();
  const visit = (node: ts.Node): void => {
    if (ts.isStringLiteralLike(node) && node.text.length > 1 && node.text.length < 200) {
      literals.add(node.text);
    }
    node.forEachChild(visit);
  };
  visit(source);
  return [...literals];
}

/** Infers what a file *is* from its content, falling back to path shape. */
export function inferRole(relative: string, node: Omit<FileNode, 'role'>): StructuralRole {
  if (node.isTest) return 'TEST';
  if (node.routes.length) return 'ROUTE';
  if (node.cliCommands.length) return 'CLI';

  const base = path.posix.basename(relative).toLowerCase();
  if (/^(index|main|server|app)\.[cm]?[jt]sx?$/.test(base)) return 'ENTRYPOINT';
  if (/(^|\/)(config|configuration|settings)(\/|\.)/.test(relative.toLowerCase())) return 'CONFIG';

  const declaresOnlyTypes =
    node.symbols.length > 0 && node.symbols.every(symbol => symbol.kind === 'interface' || symbol.kind === 'type' || symbol.kind === 'enum');
  if (declaresOnlyTypes) return 'TYPE';

  if (/(^|\/)(models?|entities|schema)(\/|\.)/.test(relative.toLowerCase())) return 'MODEL';
  if (/(^|\/)(controllers?)(\/|\.)/.test(relative.toLowerCase())) return 'CONTROLLER';
  if (/(^|\/)(services?|domain)(\/|\.)/.test(relative.toLowerCase())) return 'SERVICE';
  if (node.symbols.some(symbol => symbol.kind === 'class' || symbol.kind === 'function')) return 'SERVICE';
  return 'UNKNOWN';
}

export interface BuildGraphInput {
  worktreePath: string;
  /** Repo-relative candidate universe. Usually every tracked source file. */
  filePaths: string[];
  maxFileBytes?: number;
  maxFiles?: number;
}

export function buildRepoGraph(input: BuildGraphInput): RepoGraph {
  const startedAt = Date.now();
  const maxFileBytes = input.maxFileBytes ?? 256 * 1024;
  const files = new Map<string, FileNode>();
  const allMounts: MountPoint[] = [];

  const considered = input.filePaths
    .filter(relative => !isBinaryPath(relative))
    .filter(relative => /\.[cm]?[jt]sx?$/.test(relative))
    .slice(0, input.maxFiles ?? 4000);

  for (const relative of considered) {
    const resolved = resolveWithinWorktree(input.worktreePath, relative);
    if (!resolved.ok) continue;
    const text = readSource(resolved.absolute!, maxFileBytes);
    if (text === null) continue;

    let source: ts.SourceFile;
    try {
      source = ts.createSourceFile(resolved.absolute!, text, ts.ScriptTarget.Latest, true);
    } catch {
      continue;
    }

    const { routes, mounts, cli } = parseRoutesAndMounts(relative, source);
    const imports: string[] = [];
    const importBindings: Record<string, string> = {};

    for (const statement of source.statements) {
      if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier)) continue;
      const target = resolveModule(input.worktreePath, relative, statement.moduleSpecifier.text);
      if (!target) continue;
      imports.push(target);
      const clause = statement.importClause;
      if (clause?.name) importBindings[clause.name.text] = target;
      if (clause?.namedBindings && ts.isNamedImports(clause.namedBindings)) {
        for (const element of clause.namedBindings.elements) importBindings[element.name.text] = target;
      }
      if (clause?.namedBindings && ts.isNamespaceImport(clause.namedBindings)) {
        importBindings[clause.namedBindings.name.text] = target;
      }
    }
    for (const match of text.matchAll(/(?:const|let|var)\s+\{?\s*([A-Za-z0-9_,\s]+?)\s*\}?\s*=\s*require\(\s*['"](\.[^'"]+)['"]\s*\)/g)) {
      const target = resolveModule(input.worktreePath, relative, match[2]);
      if (!target) continue;
      imports.push(target);
      for (const name of match[1].split(',').map(part => part.trim()).filter(Boolean)) importBindings[name] = target;
    }
    for (const match of text.matchAll(/require\(\s*['"](\.[^'"]+)['"]\s*\)/g)) {
      const target = resolveModule(input.worktreePath, relative, match[1]);
      if (target) imports.push(target);
    }

    const node: Omit<FileNode, 'role'> = {
      path: relative,
      symbols: extractSymbols(relative, resolved.absolute!),
      imports: [...new Set(imports)],
      importBindings,
      mounts,
      importedBy: [],
      routes,
      cliCommands: cli,
      stringLiterals: stringLiteralsOf(source),
      bytes: Buffer.byteLength(text, 'utf8'),
      isTest: isTestPath(relative),
      isGenerated: isGeneratedPath(relative) || GENERATED_HEADER.test(text.slice(0, 200)),
    };

    files.set(relative, { ...node, role: inferRole(relative, node) });
  }

  // Reverse import edges.
  for (const [relative, node] of files) {
    for (const target of node.imports) {
      const imported = files.get(target);
      if (imported && !imported.importedBy.includes(relative)) imported.importedBy.push(relative);
    }
  }

  // Compose route prefixes. The prefix must follow the *specific* router that
  // was mounted, resolved through the mounting file's import bindings. Applying
  // a file's first mount prefix to every router it imports attributes prefixes
  // to unrelated route files, which then fabricates route matches during
  // ranking.
  const mountPrefixByFile = new Map<string, string>();
  for (const [relative, node] of files) {
    for (const mount of node.mounts) {
      if (!mount.binding) continue;
      const target = node.importBindings[mount.binding];
      if (!target) continue;
      const mounted = files.get(target);
      if (!mounted?.routes.length) continue;
      if (!mountPrefixByFile.has(target)) mountPrefixByFile.set(target, mount.prefix);
      allMounts.push({ prefix: mount.prefix, filePath: relative, resolvedPath: target });
    }
  }

  const routes: RouteDefinition[] = [];
  for (const node of files.values()) {
    for (const route of node.routes) {
      const prefix = mountPrefixByFile.get(node.path);
      route.fullPath = prefix ? composeRoutePath(prefix, route.routePath) : route.routePath;
      routes.push(route);
    }
  }

  return { worktreePath: input.worktreePath, files, routes, mounts: allMounts, buildMs: Date.now() - startedAt };
}
