/**
 * Phase 34H — PR Generator
 * Generates structured PR metadata and branch names.
 * Actual git operations are executed by the dispatched model/human dev.
 */

import { TaskClassification } from './task-classifier';
import { RoutingDecision } from './routing-engine';
import { ReviewResult } from './review-engine';

export interface PRSpec {
  branch:      string;
  title:       string;
  body:        string;
  labels:      string[];
  reviewers:   string[];
  is_draft:    boolean;
}

function branchName(taskId: string, taskType: string, domain: string): string {
  const prefix =
    taskType === 'bugfix'     ? 'fix' :
    taskType === 'feature'    ? 'feature' :
    taskType === 'refactor'   ? 'refactor' :
    taskType === 'deployment' ? 'release' :
    'hotfix';
  const slug = domain.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const id   = taskId.split('-').pop()?.toLowerCase() || 'task';
  return `${prefix}/${slug}-${id}`;
}

export function generatePR(
  taskId:         string,
  objective:      string,
  project:        string,
  classification: TaskClassification,
  routing:        RoutingDecision,
  review:         ReviewResult,
  testSummary?:   string,
): PRSpec {
  const branch = branchName(taskId, classification.task_type, classification.domain);

  const labels: string[] = [classification.task_type, classification.complexity];
  if (classification.is_production) labels.push('production');
  if (classification.domain !== 'general') labels.push(classification.domain);

  const reviewers = routing.escalate_human ? ['liemdo28'] : [];

  const riskLevel =
    classification.complexity === 'critical' ? '🔴 Critical' :
    classification.complexity === 'high'     ? '🟠 High' :
    classification.complexity === 'medium'   ? '🟡 Medium' : '🟢 Low';

  const checksTable = review.checks.map(c =>
    `| ${c.name} | ${c.passed ? '✅' : '❌'} | ${c.score}/20 | ${c.detail} |`
  ).join('\n');

  const body = `## Problem
${objective}

## Root Cause
_To be documented by ${routing.model_name} during implementation_

## Fix / Implementation
_Describe what was changed and why_

## Evidence
- Task ID: \`${taskId}\`
- Model: ${routing.model_name} (confidence: ${routing.confidence}%)
- Classification: ${classification.domain} / ${classification.language} / ${classification.task_type}

## Code Review Results (Score: ${review.total_score}/100)
| Check | Status | Score | Detail |
|-------|--------|-------|--------|
${checksTable}

${review.blockers.length ? `### ⚠️ Blockers\n${review.blockers.map(b => `- ${b}`).join('\n')}` : ''}

${testSummary ? `## Test Results\n${testSummary}` : '## Tests\n_Run test suite before merge_'}

## Risk
${riskLevel} — ${classification.complexity} complexity ${classification.is_production ? '— **PRODUCTION CHANGE**' : ''}

## Rollback
\`\`\`bash
git revert HEAD
pm2 restart mi-core
\`\`\`

---
_Generated by Mi Engineering Division — Task ${taskId}_
_Model: ${routing.model_name} · Branch: \`${branch}\`_`;

  return {
    branch,
    title:     `[${classification.task_type.toUpperCase()}] ${objective.slice(0, 72)}`,
    body,
    labels,
    reviewers,
    is_draft:  routing.escalate_human || review.total_score < 85,
  };
}
